### PR TITLE
Tinkering/zen arcadia

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by kylog** [comment]
Things to think about:
- [ ] one
- [ ] other

**Comment by zen-arcadia** [comment]
Add zen-arcade config file superfluous text

**Comment by zen-arcadia** [comment]
rename superfluous text

**Comment by zen-arcadia** [comment]
The commit summary 'Add zen-arcade config file' did not conform to this repo's requirements

**Comment by zen-arcadia** [comment]
The commit summary 'rename' did not conform to this repo's requirements

**Comment by zen-arcadia** [comment]
The commit summary 'Add zen-arcade config file' did not conform to this repo's requirements

**Comment by zen-arcadia** [comment]
The commit summary 'rename' did not conform to this repo's requirements

**Comment by zen-arcadia** [comment]
The commit summary 'Add zen-arcade config file' did not conform to this repo's requirements

**Comment by zen-arcadia** [comment]
The commit summary 'rename' did not conform to this repo's requirements

**Pull request closed without merging**
